import { Inter } from 'next/font/google';
import styles from './globals.css';

import Header from './components/Header/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Solana',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${styles.container}`}>
        <Header />
          {children}
        </body>
    </html>
  );
}
